name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Install Railway CLI
      run: npm install -g railway

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Deploy to Railway
      if: success()
      run: railway deploy --token $RAILWAY_TOKEN
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
