name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to Render
      if: success()
      uses: render-actions/deploy@1.3.0
      with:
        render_token: ${{ secrets.RENDER_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        build_command: npm run build
        start_command: npm start
